### ISSUE TITLE
Instant repolling

### ISSUE THREAD

**Issue by remofritzsche** [sitrox/workhorse#15]
Currently, the poller only obtains one job per poll and queue. If a queue contains more than one job, multiple polls are required for all of the jobs to be processed. It may be worth a thought to adapt this to memory-queue all jobs ready for execution when obtaining them using a poll.

**Comment by tschoppi** [comment]
Some questions came to mind while reading this proposal:

- What is the end goal with this idea? To make the polling interval larger? At the cost of what? (What trade-off are we considering here?)
- When are these jobs set to `locked` in the database?
- What happens when the process is shut down while holding jobs in the memory queue?

I see how this could be beneficial for very fast jobs (execute more jobs within one polling interval) but that could also mean that our default/recommended polling intervals are not sufficiently tuned to realistic scenarios.

Maybe we would be better served by adding a job queue length monitor that could notify (via email, log watcher, what-have-you) the administrator when "things" (to be further specified) go amiss.

**Comment by remofritzsche** [comment]
Good points. Consider the following example:

> 50 jobs are inserted into the same queue at once. The polling interval is set to 1 minute, and each job only takes a second. This would mean that it takes 50+ minutes for all the jobs to be performed.

What about a feature along the lines of *instant repolling*: Using a global or worker-specific setting, `instant_repolling` can be enabled. This ensures that, after a job is executed, the poller immediately repolls for new jobs in the same queue. If none exists, it will resume polling in the usual polling interval.

What do you think?

**Comment by tschoppi** [comment]
I like this idea. Once a worker returns, it can be given a new job, provided such a job is available.

Not sure about "same queue", though. This could lead to queue-locked workers, ignoring other parameters such as `perform_at`. I would suggest keeping the _instant repoll_ as general as possible.

**Comment by remofritzsche** [comment]
The PR has been updated, see commit messages for the simplifications performed.

One more issue comes to mind though: The instant re-polling happens even when the number of free pool slots was bigger than the number of the jobs available. Consider the following example:

- Pool size = 3
- Poller polls and receives 1 job
- The job is being processed while 2 pool slots remain unused
- After the job run, an instant repoll occurs, even though there was capacity for performing more (at this time non-existing) jobs at time of the original poll

Is this a drawback?

**Comment by tschoppi** [comment]
This is, in my mind, a minuscule performance drawback. The instant repoll, as described in your scenario, is not required. But it will also not break anything.
If this behavior turns out to be a problem, simply disabling the instant repoll after job execution on the condition `waiting_jobs == available_threads` would do the trick.

**Comment by remofritzsche** [comment]
Agreed. Let's merge this PR for now. If this issue ever should arise, which I doubt it will, we can still implement this additional check. Let's stick to the current behavior for the sake of code simplicity.

**Comment by remofritzsche** [comment]
PR is merged.
